### ISSUE TITLE
Problem with API put request for regular user, route api/teachers/teacher/<pk>

### ISSUE THREAD

**Issue by kadusicadi** [aheacon/school_enrollment#5]
# Solution
In django settings.py set the DEBUG option to True

# Problem analysis
## Request and response data analysis

Start data before the request in JSON format:
```json
{
	"id": 4,
	"is_superuser": false,
	"first_name": "Test22",
	"last_name": "Test",
	"is_staff": false,
	"email": "test2@test.ba",
	"is_verified": true,
	"school_id": 2,
	"course_code": "EL-meh"
}
```
Data that should be sent in a PUT request:
```json
{
	"id": 4,
	"is_superuser": false,
	"first_name": "Test223",  - updated field
	"last_name": "Test",
	"is_staff": false,
	"email": "test2@test.ba",
	"is_verified": true,
	"school_id": 2,
	"course_code": "EL-meh"
}
```
Response:
```bash
GET /api/teachers/teacher/4/?_content_type=application%2Fjson&_content=%7B%0D%0A++++%22id%22%3A+4%2C%0D%0A++++%22is_superuser%22%3A+false%2C%0D%0A++++%22first_name%22%3A+%22Test22%22%2C%0D%0A++++%22last_name%22%3A+%22Test%22%2C%0D%0A++++%22is_staff%22%3A+false%2C%0D%0A++++%22email%22%3A+%22test2%40test.ba%22%2C%0D%0A++++%22is_verified%22%3A+true%2C%0D%0A++++%22school_id%22%3A+2%2C%0D%0A++++%22course_code%22%3A+%22EL-meh%22%0D%0A%7D
HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
```
```json
{
    "id": 4,
    "is_superuser": false,
    "first_name": "Test22",
    "last_name": "Test",
    "is_staff": false,
    "email": "test2@test.ba",
    "is_verified": true,
    "school_id": 2,
    "course_code": "EL-meh"
}
```
The data isn't updated after the request. Also the response is a GET request?

## View analysis

TeacherViewDetail view that causes problems:
```
import pdb # importing python debugger
class TeacherViewDetail(RetrieveUpdateDestroyAPIView):
    serializer_class= TeacherSerializerUpdate
    '''
    All authenticated users can update/delete user, but this shouldn't be
    allowed in frontend.
    Only superuser can see the list of all users.
    '''
    permission_classes= [IsAuthenticated]

    def get_queryset(self):
        return Teacher.objects.all()

    # Make sure that normal users can get only current form to update
    def get(self, request, *args, **kwargs):
        pk= self.kwargs['pk']
        t_id= request.user.id
        # Only superuser can get list of data to update
        pdb.set_trace() # debug breakpoint
        if pk != t_id and t_id:
            teacher= Teacher.objects.get(id= t_id)
            if teacher.is_superuser == False:
                return Response({'message':'Teacher not authorized to view teacher list'},
                       status=status.HTTP_203_NON_AUTHORITATIVE_INFORMATION)
        return super().get(request, *args, **kwargs)
```

## Python debugger analysis

Data from python debugger (pdb):
```bash
(Pdb) print(request)       
<rest_framework.request.Request: GET '/api/teachers/teacher/6/?_content_type=application%2Fjson&_content=%7B%0D%0A++++%22id%22%3A+6%2C%0D%0A++++%22is_superuser%22%3A+true%2C%0D%0A++++%22first_name%22%3A+%22Adi22%22%2C%0D%0A++++%22last_name%22%3A+%22Kadusic%22%2C%0D%0A++++%22is_staff%22%3A+true%2C%0D%0A++++%22email%22%3A+%22adi.kadusic%40eacon.ba%22%2C%0D%0A++++%22is_verified%22%3A+false%2C%0D%0A++++%22school_id%22%3A+1%2C%0D%0A++++%22course_code%22%3A+%22EL%22%0D%0A%7D'>
(Pdb) print(request.data)
{}

(Pdb) print(response)
<Response status_code=200, "text/html; charset=utf-8">
(Pdb) print(response.data)
{'id': 6, 'is_superuser': True, 'first_name': 'Adi', 'last_name': 'Kadusic', 'is_staff': True, 'email': 'adi.kadusic@eacon.ba', 'is_verified': False, 'school_id': 1, 'course_code': 'EL'}
```
Note that the request body is empty, does that cause the problem? Why is the body empty?

## Django backend test analysis

```
def test_update_teacher_teacher_detail(self):
"""
UPDATE: Test updating teacher with specific id (200);
Note: Not passing the password in the data;
"""
self.log_me_with_jwt()
url= reverse('teacher-detail', args= (self.teacher.id,))
"""
We didn't updated school_id and _course_code, since they are FK.
We need data in order to make right request, instead we will get 400
(Bad request)
"""
data= self.testData
resp= self.client.put(url, data)
self.assertEqual(resp.status_code, status.HTTP_200_OK, resp.data)
self.teacher.refresh_from_db()
self.assertEqual(self.teacher.email, self.testData['email'])
self.assertEqual(self.teacher.first_name, self.testData['first_name'])
self.assertEqual(self.teacher.last_name, self.testData['last_name'])
print("\nUrl: " + url + " - Succesfully updated teacher.")
```

Backend test result:
```bash
Url: /api/teachers/teacher/2/ - Succesfully updated teacher.
```

## Postman analysis

Postman tests for update works.
Date after GET request:
```json
{
    "id": 4,
    "is_superuser": false,
    "first_name": "Test22",
    "last_name": "Test",
    "is_staff": false,
    "email": "test2@test.ba",
    "is_verified": true,
    "school_id": 2,
    "course_code": "EL-meh"
}
```
Data in PUT request body:
```json
{
    "id": 4,
    "is_superuser": false,
    "first_name": "Test22aa", - updated field
    "last_name": "Test",
    "is_staff": false,
    "email": "test2@test.ba",
    "is_verified": true,
    "school_id": 2,
    "course_code": "EL-meh"
}
```
PUT request response:
```json
{
    "id": 4,
    "is_superuser": false,
    "first_name": "Test22aa",
    "last_name": "Test",
    "is_staff": false,
    "email": "test2@test.ba",
    "is_verified": true,
    "school_id": 2,
    "course_code": "EL-meh"
}
```

## Browser analysis

Backend works as expected using postman. It seems that the problem is with the browser, it always sends a get request (even if the method is PUT):
```bash
GET /api/teachers/teacher/4/?_content_type=application%2Fjson&_content=%7B%0D%0A++++%22id%22%3A+4%2C%0D%0A++++%22is_superuser%22%3A+false%2C%0D%0A++++%22first_name%22%3A+%22Test22%22%2C%0D%0A++++%22last_name%22%3A+%22Test%22%2C%0D%0A++++%22is_staff%22%3A+false%2C%0D%0A++++%22email%22%3A+%22test2%40test.ba%22%2C%0D%0A++++%22is_verified%22%3A+true%2C%0D%0A++++%22school_id%22%3A+2%2C%0D%0A++++%22course_code%22%3A+%22EL-meh%22%0D%0A%7D
HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
```
Browser doesn't seem to render CSS, it only renders pure HTML
Inspect element errors:
```
The resource from “http://localhost:8000/static/admin/css/base.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/js/nav_sidebar.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/css/dark_mode.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/js/theme.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
Loading failed for the <script> with source “http://localhost:8000/static/admin/js/theme.js”. [admin:9:49](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/css/base.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/js/nav_sidebar.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
Loading failed for the <script> with source “http://localhost:8000/static/admin/js/nav_sidebar.js”. [admin:13:55](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/css/nav_sidebar.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/css/dashboard.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[admin](http://localhost:8000/admin/)
The resource from “http://localhost:8000/static/admin/css/responsive.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by aheacon** [comment]
Gdje je test u backendu za ovo ?

**Comment by aheacon** [comment]
MOzes li pokazati da si koristio `import pdb` i sta dobivas za koju rutu, kakav request i kakve ostale parametre ?

**Comment by Faariis** [comment]
def test_update_teacher_teacher_detail(self):
    """
    UPDATE: Test updating teacher with specific id (200);
    Note: Not passing the password in the data;
    """
    self.log_me_with_jwt()
    url= reverse('teacher-detail', args= (self.teacher.id,))
    """
    We didn't updated `school_id` and `_course_code`, since they are FK.
    We need data in order to make right request, instead we will get 400
    (Bad request)
    """
    data= self.testData
    resp= self.client.put(url, data)
    self.assertEqual(resp.status_code, status.HTTP_200_OK, resp.data)
    self.teacher.refresh_from_db()
    self.assertEqual(self.teacher.email, self.testData['email'])
    self.assertEqual(self.teacher.first_name, self.testData['first_name'])
    self.assertEqual(self.teacher.last_name, self.testData['last_name'])
    print("\nUrl: " + url + " - Succesfully updated teacher.")

**Comment by aheacon** [comment]
@faris hajde ponov provjeri test, ako ga nema, napravi ga, teacher u request kojim ti radis u backendu je superuser, a trebao bi da ne bude superuser kao kod Adija.

**Comment by Faariis** [comment]
Ovo je samo get:

(Pdb) print(request)
<rest_framework.request.Request: GET '/api/teachers/teacher/1/'>
(Pdb) print(request.data)
{}
(Pdb) print(response)
<Response status_code=200, "text/html; charset=utf-8">
(Pdb) print(response.data)
{'id': 1, 'is_superuser': True, 'first_name': 'Anel', 'last_name': 'Husakovic', 'is_staff': True, 'email': 'a@anel.ba', 'is_verified': True, 'school_id': 1, 'course_code': 'RTiA'}
(Pdb)

Prije put: 

(Pdb) print(response)
<Response status_code=200, "text/html; charset=utf-8">
(Pdb) print(response.data)
{'id': 14, 'is_superuser': False, 'first_name': 'Nikooo', 'last_name': 'NijeSuperuser', 'is_staff': True, 'email': 'nijesuperuser@maill.com', 
'is_verified': False, 'school_id': 1, 'course_code': 'RTiA'}
(Pdb)

Poslije put:

(Pdb) print(response)
<Response status_code=200, "text/html; charset=utf-8">
(Pdb) print(response.data)
{'id': 14, 'is_superuser': False, 'first_name': 'Nikoo', 'last_name': 'NijeSuperuser', 'is_staff': True, 'email': 'nijesuperuser@maill.com', 'is_verified': False, 'school_id': 1, 'course_code': 'RTiA'}
(Pdb)

**Comment by aheacon** [comment]
@kadusicadi  vezano za browser problem provjeri `DEBUG` varijablu i vidi [ref](https://stackoverflow.com/questions/62555499/django-react-the-resource-was-blocked-due-to-mime-type-text-html-mismatch), ako je `OFF` postavi je na `ON` i trebalo bi raditi. Ako je `ON` pokreni server `./manage.py runserver --insecure`.
Malo se tesko snaci u issue, probaj  formatirati tekst koristeci [basic markdown formating rules](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Npr. nije jasno gdje si stavio debugger. Ako zelis da posmatras za `put` onda moras staviti debug point  u `put` funkciju ili koja je nativna u Djangu (za klasu koja je parent odredjenog view-a)  ili koju ces sam napisati koja ce override nativnu funkciju.

**Comment by kadusicadi** [comment]
The cause of this problem was that the **DEBUG** variable in the **settings.py** was not True. The solution is to set it to **True**.

**Comment by kadusicadi** [comment]
The solution to the browser problem was also to set the django **DEBUG** variable to true.
